### ndarry的索引(index),切割(slice)

In [1]:
import numpy as np

arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]

array([7, 8, 9])

In [2]:
import random
random.randint(50,100)

81

In [3]:
np.random.randint(50, 101, size=5)
scores = np.random.randint(50,101, size=(50, 5))
scores.size
scores.shape

(50, 5)

In [4]:
scores[:,0]
scores[:,0:1]

array([[98],
       [80],
       [66],
       [74],
       [56],
       [81],
       [97],
       [67],
       [84],
       [71],
       [96],
       [88],
       [76],
       [73],
       [84],
       [87],
       [65],
       [66],
       [76],
       [71],
       [50],
       [53],
       [89],
       [76],
       [68],
       [78],
       [58],
       [85],
       [71],
       [83],
       [84],
       [93],
       [52],
       [72],
       [96],
       [65],
       [51],
       [74],
       [51],
       [59],
       [81],
       [56],
       [72],
       [78],
       [58],
       [78],
       [96],
       [84],
       [74],
       [68]], dtype=int32)

In [7]:
scores[0,:]
scores[0:1,:]

array([[98, 59, 95, 77, 87]], dtype=int32)

In [6]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)

array([83.2, 79.6, 79. , 84.4, 63.4, 73. , 85. , 81.2, 85.8, 69.6, 82.8,
       70.8, 70.8, 74.4, 80.6, 84.8, 67.8, 74.6, 78. , 70.4, 76. , 65.2,
       72. , 79. , 72.6, 71.4, 80.8, 60.6, 69.8, 63.6, 72.6, 67.6, 81.6,
       67. , 80.6, 73. , 67.8, 75.6, 66. , 74.8, 77. , 76.4, 70.2, 75.6,
       62.4, 73.2, 69.8, 78.2, 75.2, 72.6])

In [8]:
#使用比較運算子
arr = np.random.randn(5)
arr > 0

array([False, False,  True,  True,  True])

In [9]:
np.where(arr > 0, 1, 0)

array([0, 0, 1, 1, 1])

In [10]:
np.where(arr > 0, 1, arr)

array([-1.34771912, -0.43255823,  1.        ,  1.        ,  1.        ])