https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

### numpy的索引和切割

In [1]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[93, 57, 77, 97, 86],
       [61, 77, 66, 91, 70],
       [78, 66, 50, 92, 90],
       [74, 87, 59, 68, 75],
       [97, 82, 92, 58, 90]], dtype=int32)

In [2]:
scores[:3,2:]

array([[77, 97, 86],
       [66, 91, 70],
       [50, 92, 90]], dtype=int32)

In [3]:
scores[4]
scores[4,:]
scores[4:,:]

array([[97, 82, 92, 58, 90]], dtype=int32)

In [4]:
scores[:,:2]

array([[93, 57],
       [61, 77],
       [78, 66],
       [74, 87],
       [97, 82]], dtype=int32)

### numpy的統計工具

In [6]:
scores = np.random.randint(50,101,size=(5,5))
scores

array([[68, 58, 76, 81, 82],
       [53, 57, 69, 53, 56],
       [87, 55, 95, 57, 77],
       [96, 89, 99, 50, 75],
       [60, 75, 99, 74, 89]], dtype=int32)

In [7]:
scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]

array([365, 288, 371, 409, 397], dtype=int32)

In [9]:
#加總
np.sum(scores,axis=1)

array([365, 288, 371, 409, 397])

In [10]:
#平均
np.mean(scores, axis=1)

array([73. , 57.6, 74.2, 81.8, 79.4])

In [11]:
#最大
np.max(scores,axis=1)

array([82, 69, 95, 99, 99], dtype=int32)

In [12]:
#最小
np.min(scores,axis=1)

array([58, 53, 55, 50, 60], dtype=int32)

In [13]:
#中間數
np.mean(scores,axis=1)

array([73. , 57.6, 74.2, 81.8, 79.4])

In [14]:
#標準差
np.std(scores,axis=1)

array([ 8.98888202,  5.91945943, 15.9298462 , 17.92651667, 13.42534916])