In [1]:
import numpy as np

In [2]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.random.rand(3, 4)

array([[0.5778395 , 0.66112998, 0.78513613, 0.73179196],
       [0.2010298 , 0.9812352 , 0.55760038, 0.12484463],
       [0.26755507, 0.75792242, 0.56037133, 0.01469166]])

In [9]:
scores = np.random.randint(50,101,size=(50, 5))
scores

array([[ 87,  74,  88,  76,  78],
       [ 82,  53,  72,  69,  67],
       [ 80,  90,  62, 100,  68],
       [ 63,  92,  57,  74,  96],
       [ 75,  68,  83,  72,  68],
       [ 50,  63,  62,  98,  72],
       [ 79,  63,  64,  94,  91],
       [ 92,  58,  88,  53,  67],
       [ 74,  96,  88,  89,  99],
       [ 94,  65,  84,  58,  90],
       [ 93,  66,  87,  55,  51],
       [ 54,  76,  93,  73,  84],
       [ 86,  53,  86,  86,  99],
       [ 84,  91,  68,  65,  55],
       [ 68,  55,  55,  98,  93],
       [ 50,  82,  91,  71,  98],
       [ 58,  62,  86,  83,  81],
       [ 58,  55,  69,  86,  96],
       [ 92,  95,  50,  95,  80],
       [ 54,  91,  99,  92,  96],
       [ 98,  98,  60,  51,  63],
       [ 82,  59,  75, 100,  61],
       [ 76,  82,  50,  55,  79],
       [ 99,  87,  64,  60,  69],
       [ 68,  50,  61,  77,  80],
       [ 87,  54,  86,  93,  76],
       [ 71,  99,  52,  96,  93],
       [ 58,  86,  92,  90,  94],
       [ 51,  55,  67,  93,  68],
       [ 92,  